Dev/2.0
SwallowMC/SouthFox pull request #10
Opened 2021-04-07 13:01 UTC by zimzaza4

添加Floodgate? (误)

2021-04-08 15:02 UTC, SinanGentoo requested changes
由于skript-reflect不支持带objects类型的传输，故换用新的方法来传递群号，请参照KitFox-CORE.sk修改

2021-04-08 21:53 UTC, zimzaza4 commented
哦

2021-04-08 21:58 UTC, zimzaza4 commented
我记得MCQQBot群号是个number来着
az

2021-04-09 10:39 UTC, SinanGentoo commented
> 我记得MCQQBot群号是个number来着
> az

McQQbot老版的遗留问题（老版qq群给的是text）

2021-04-09 10:41 UTC, merged

2021-04-09 10:42 UTC, zimzaza4 commented
这个... 
Floodgate-Skript 是有2.0的...
在另一个分支里(
Floodgate2.0(reflect)
可以暂时先删掉

2021-04-09 10:48 UTC, SinanGentoo commented
> 这个... 
> Floodgate-Skript 是有2.0的...
> 在另一个分支里(
> Floodgate2.0(reflect)
> 可以暂时先删掉

okay